// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MasterClient is the client API for Master service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MasterClient interface {
	Accept(ctx context.Context, in *ListenerRequest, opts ...grpc.CallOption) (Master_AcceptClient, error)
	Open(ctx context.Context, in *FileOpen, opts ...grpc.CallOption) (*FileHandler, error)
}

type masterClient struct {
	cc grpc.ClientConnInterface
}

func NewMasterClient(cc grpc.ClientConnInterface) MasterClient {
	return &masterClient{cc}
}

func (c *masterClient) Accept(ctx context.Context, in *ListenerRequest, opts ...grpc.CallOption) (Master_AcceptClient, error) {
	stream, err := c.cc.NewStream(ctx, &Master_ServiceDesc.Streams[0], "/service.Master/Accept", opts...)
	if err != nil {
		return nil, err
	}
	x := &masterAcceptClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Master_AcceptClient interface {
	Recv() (*AcceptResponse, error)
	grpc.ClientStream
}

type masterAcceptClient struct {
	grpc.ClientStream
}

func (x *masterAcceptClient) Recv() (*AcceptResponse, error) {
	m := new(AcceptResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *masterClient) Open(ctx context.Context, in *FileOpen, opts ...grpc.CallOption) (*FileHandler, error) {
	out := new(FileHandler)
	err := c.cc.Invoke(ctx, "/service.Master/Open", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MasterServer is the server API for Master service.
// All implementations must embed UnimplementedMasterServer
// for forward compatibility
type MasterServer interface {
	Accept(*ListenerRequest, Master_AcceptServer) error
	Open(context.Context, *FileOpen) (*FileHandler, error)
	mustEmbedUnimplementedMasterServer()
}

// UnimplementedMasterServer must be embedded to have forward compatible implementations.
type UnimplementedMasterServer struct {
}

func (UnimplementedMasterServer) Accept(*ListenerRequest, Master_AcceptServer) error {
	return status.Errorf(codes.Unimplemented, "method Accept not implemented")
}
func (UnimplementedMasterServer) Open(context.Context, *FileOpen) (*FileHandler, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Open not implemented")
}
func (UnimplementedMasterServer) mustEmbedUnimplementedMasterServer() {}

// UnsafeMasterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MasterServer will
// result in compilation errors.
type UnsafeMasterServer interface {
	mustEmbedUnimplementedMasterServer()
}

func RegisterMasterServer(s grpc.ServiceRegistrar, srv MasterServer) {
	s.RegisterService(&Master_ServiceDesc, srv)
}

func _Master_Accept_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListenerRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MasterServer).Accept(m, &masterAcceptServer{stream})
}

type Master_AcceptServer interface {
	Send(*AcceptResponse) error
	grpc.ServerStream
}

type masterAcceptServer struct {
	grpc.ServerStream
}

func (x *masterAcceptServer) Send(m *AcceptResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Master_Open_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileOpen)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).Open(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Master/Open",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).Open(ctx, req.(*FileOpen))
	}
	return interceptor(ctx, in, info, handler)
}

// Master_ServiceDesc is the grpc.ServiceDesc for Master service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Master_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.Master",
	HandlerType: (*MasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Open",
			Handler:    _Master_Open_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Accept",
			Handler:       _Master_Accept_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "master.proto",
}
