// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.17.3
// source: process-helper/extender.proto

package process_helper

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type InstallExtender struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Extends []*ExtenderBasicInfo `protobuf:"bytes,1,rep,name=extends,proto3" json:"extends,omitempty"`
}

func (x *InstallExtender) Reset() {
	*x = InstallExtender{}
	if protoimpl.UnsafeEnabled {
		mi := &file_process_helper_extender_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstallExtender) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallExtender) ProtoMessage() {}

func (x *InstallExtender) ProtoReflect() protoreflect.Message {
	mi := &file_process_helper_extender_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallExtender.ProtoReflect.Descriptor instead.
func (*InstallExtender) Descriptor() ([]byte, []int) {
	return file_process_helper_extender_proto_rawDescGZIP(), []int{0}
}

func (x *InstallExtender) GetExtends() []*ExtenderBasicInfo {
	if x != nil {
		return x.Extends
	}
	return nil
}

type ExtenderBasicInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`     // {group}:{project}:{version}
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // {group}:{project}
	Group   string `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	Project string `protobuf:"bytes,4,opt,name=project,proto3" json:"project,omitempty"`
	Version string `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *ExtenderBasicInfo) Reset() {
	*x = ExtenderBasicInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_process_helper_extender_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExtenderBasicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtenderBasicInfo) ProtoMessage() {}

func (x *ExtenderBasicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_process_helper_extender_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtenderBasicInfo.ProtoReflect.Descriptor instead.
func (*ExtenderBasicInfo) Descriptor() ([]byte, []int) {
	return file_process_helper_extender_proto_rawDescGZIP(), []int{1}
}

func (x *ExtenderBasicInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExtenderBasicInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExtenderBasicInfo) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ExtenderBasicInfo) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *ExtenderBasicInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type Extenders struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Extenders []*ExtenderMsg `protobuf:"bytes,1,rep,name=extenders,proto3" json:"extenders,omitempty"`
}

func (x *Extenders) Reset() {
	*x = Extenders{}
	if protoimpl.UnsafeEnabled {
		mi := &file_process_helper_extender_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Extenders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Extenders) ProtoMessage() {}

func (x *Extenders) ProtoReflect() protoreflect.Message {
	mi := &file_process_helper_extender_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Extenders.ProtoReflect.Descriptor instead.
func (*Extenders) Descriptor() ([]byte, []int) {
	return file_process_helper_extender_proto_rawDescGZIP(), []int{2}
}

func (x *Extenders) GetExtenders() []*ExtenderMsg {
	if x != nil {
		return x.Extenders
	}
	return nil
}

type ExtenderMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicInfo *ExtenderBasicInfo `protobuf:"bytes,1,opt,name=basicInfo,proto3" json:"basicInfo,omitempty"`
	Plugins   []*PluginMsg       `protobuf:"bytes,2,rep,name=plugins,proto3" json:"plugins,omitempty"`
}

func (x *ExtenderMsg) Reset() {
	*x = ExtenderMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_process_helper_extender_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExtenderMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtenderMsg) ProtoMessage() {}

func (x *ExtenderMsg) ProtoReflect() protoreflect.Message {
	mi := &file_process_helper_extender_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtenderMsg.ProtoReflect.Descriptor instead.
func (*ExtenderMsg) Descriptor() ([]byte, []int) {
	return file_process_helper_extender_proto_rawDescGZIP(), []int{3}
}

func (x *ExtenderMsg) GetBasicInfo() *ExtenderBasicInfo {
	if x != nil {
		return x.BasicInfo
	}
	return nil
}

func (x *ExtenderMsg) GetPlugins() []*PluginMsg {
	if x != nil {
		return x.Plugins
	}
	return nil
}

type PluginMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // {group}:{project}:{name}
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Group   string `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	Project string `protobuf:"bytes,4,opt,name=project,proto3" json:"project,omitempty"`
}

func (x *PluginMsg) Reset() {
	*x = PluginMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_process_helper_extender_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginMsg) ProtoMessage() {}

func (x *PluginMsg) ProtoReflect() protoreflect.Message {
	mi := &file_process_helper_extender_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginMsg.ProtoReflect.Descriptor instead.
func (*PluginMsg) Descriptor() ([]byte, []int) {
	return file_process_helper_extender_proto_rawDescGZIP(), []int{4}
}

func (x *PluginMsg) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PluginMsg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginMsg) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *PluginMsg) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

var File_process_helper_extender_proto protoreflect.FileDescriptor

var file_process_helper_extender_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x2d, 0x68, 0x65, 0x6c, 0x70, 0x65, 0x72,
	0x2f, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x68, 0x65, 0x6c, 0x70, 0x65, 0x72, 0x22,
	0x4e, 0x0a, 0x0f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x12, 0x3b, 0x0a, 0x07, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x68, 0x65,
	0x6c, 0x70, 0x65, 0x72, 0x2e, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x42, 0x61, 0x73,
	0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x73, 0x22,
	0x81, 0x01, 0x0a, 0x11, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x42, 0x61, 0x73, 0x69,
	0x63, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12,
	0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x22, 0x46, 0x0a, 0x09, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x73,
	0x12, 0x39, 0x0a, 0x09, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x68, 0x65,
	0x6c, 0x70, 0x65, 0x72, 0x2e, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4d, 0x73, 0x67,
	0x52, 0x09, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x22, 0x83, 0x01, 0x0a, 0x0b,
	0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x3f, 0x0a, 0x09, 0x62,
	0x61, 0x73, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21,
	0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x68, 0x65, 0x6c, 0x70, 0x65, 0x72, 0x2e,
	0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x42, 0x61, 0x73, 0x69, 0x63, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x33, 0x0a, 0x07,
	0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x68, 0x65, 0x6c, 0x70, 0x65, 0x72, 0x2e, 0x50,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x4d, 0x73, 0x67, 0x52, 0x07, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x73, 0x22, 0x5f, 0x0a, 0x09, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x4d, 0x73, 0x67, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x65, 0x6f, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x72, 0x2f, 0x65, 0x6f, 0x73, 0x63, 0x2f, 0x70,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x2d, 0x68, 0x65, 0x6c, 0x70, 0x65, 0x72, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_process_helper_extender_proto_rawDescOnce sync.Once
	file_process_helper_extender_proto_rawDescData = file_process_helper_extender_proto_rawDesc
)

func file_process_helper_extender_proto_rawDescGZIP() []byte {
	file_process_helper_extender_proto_rawDescOnce.Do(func() {
		file_process_helper_extender_proto_rawDescData = protoimpl.X.CompressGZIP(file_process_helper_extender_proto_rawDescData)
	})
	return file_process_helper_extender_proto_rawDescData
}

var file_process_helper_extender_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_process_helper_extender_proto_goTypes = []interface{}{
	(*InstallExtender)(nil),   // 0: process_helper.installExtender
	(*ExtenderBasicInfo)(nil), // 1: process_helper.ExtenderBasicInfo
	(*Extenders)(nil),         // 2: process_helper.Extenders
	(*ExtenderMsg)(nil),       // 3: process_helper.ExtenderMsg
	(*PluginMsg)(nil),         // 4: process_helper.PluginMsg
}
var file_process_helper_extender_proto_depIdxs = []int32{
	1, // 0: process_helper.installExtender.extends:type_name -> process_helper.ExtenderBasicInfo
	3, // 1: process_helper.Extenders.extenders:type_name -> process_helper.ExtenderMsg
	1, // 2: process_helper.ExtenderMsg.basicInfo:type_name -> process_helper.ExtenderBasicInfo
	4, // 3: process_helper.ExtenderMsg.plugins:type_name -> process_helper.PluginMsg
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_process_helper_extender_proto_init() }
func file_process_helper_extender_proto_init() {
	if File_process_helper_extender_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_process_helper_extender_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstallExtender); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_process_helper_extender_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExtenderBasicInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_process_helper_extender_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Extenders); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_process_helper_extender_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExtenderMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_process_helper_extender_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_process_helper_extender_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_process_helper_extender_proto_goTypes,
		DependencyIndexes: file_process_helper_extender_proto_depIdxs,
		MessageInfos:      file_process_helper_extender_proto_msgTypes,
	}.Build()
	File_process_helper_extender_proto = out.File
	file_process_helper_extender_proto_rawDesc = nil
	file_process_helper_extender_proto_goTypes = nil
	file_process_helper_extender_proto_depIdxs = nil
}
